### ISSUE TITLE
Splash image appears, but Audacium does not open

### ISSUE THREAD

**Issue by Sta-ray** [SartoxSoftware/audacium#40] opened 2021-07-16 20:57 UTC
Description:
Upon opening Audacium.exe after installation using the installer, the splash image will show for a few seconds, then Audacium will not open. Task Manager shows Audacium Cross-Platform sound opening briefly then closing again

Additional Info:
 - OS: Windows 10 Build 18363.1440
 - Version Audacium v3.0.4x64

I saw a previous issue where the bug reporter had fixed the issue by reinstalling, unfortunately this did not work for me. I've also attempted adding it to my Anti-virus and firewall exceptions which also did not work.

**Comment by xxxcrow** [comment] 2021-07-17 06:53
Same here

 - OS: Windows 11 Build 22000.71
 - Version Audacium v3.0.4x64

**Comment by AnErrupTion** [comment] 2021-07-17 11:39
Can you try with the latest build from GitHub actions?

**Comment by Sta-ray** [comment] 2021-07-17 12:43
@AnErrupTion I've tried running the Audacium.exe from the latest version in Actions from 9:15 BST today, but this hasn't stopped the issue.

**Comment by xxxcrow** [comment] 2021-07-18 20:19
> 
> 
> Can you try with the latest build from GitHub actions?

Exactly the same 😄

**Comment by enterv0id** [comment] 2021-07-21 11:49
same W10

**Comment by fell-z** [comment] 2021-07-22 16:53
The same issue happens with me

- Windows 10 OS Build 19043.1083
- Version Audacium v3.0.4x64

**Comment by AnErrupTion** [comment] 2021-07-22 23:24
Can anyone try to reproduce this issue on Linux? I need to know if this issue affects Linux too.

**Comment by ApoorvaKashyap** [comment] 2021-07-23 04:05
> Can anyone try to reproduce this issue on Linux? I need to know if this issue affects Linux too.

No it doesn't. Though Audacium does take a while to start up after clicking on the launcher icon.

**Comment by Pyr-000** [comment] 2021-08-20 13:39
I'm having the same issue & exception with the installer version (July 12th) 
The July 10th portable version (7z) seems to be working fine.
(Win10 20H2 Build 19042.1165; Audacium 3.0.4-x64)
```
Faulting application name: audacium.exe, version: 3.0.4.0, time stamp: 0x60ec39c5
Faulting module name: audacium.exe, version: 3.0.4.0, time stamp: 0x60ec39c5
Exception code: 0xc0000005
Fault offset: 0x000000000070292f
```

**Comment by BorniPL** [comment] 2021-08-20 15:52
> I'm having the same issue & exception with the installer version (July 12th)
> The July 10th portable version (7z) seems to be working fine.
> (Win10 20H2 Build 19042.1165; Audacium 3.0.4-x64)
> 
> ```
> Faulting application name: audacium.exe, version: 3.0.4.0, time stamp: 0x60ec39c5
> Faulting module name: audacium.exe, version: 3.0.4.0, time stamp: 0x60ec39c5
> Exception code: 0xc0000005
> Fault offset: 0x000000000070292f
> ```

Confirmed. Extracted .7z version from 10th July directly to the C:/Program Files/Audacium/ and it started to work.

**Comment by AnErrupTion** [comment] 2021-11-17 05:45
Can anyone here try the new build from GitHub Actions to see if it fixes the problem?

**Comment by Pyr-000** [comment] 2021-11-17 12:51
The latest build from actions (CMake Build #83) on win64 seems to be working perfectly fine for me.

**Comment by MurdoMaclachlan** [comment] 2021-11-18 15:15
The latest build doesn't work for me but I'm not sure if my issue is the same one or not. I'm on Linux (Slackware Current); after the splash screen, the main window opens for a split-second before Audacium crashes. Running it in a terminal gives no output.

**Comment by AnErrupTion** [comment] 2021-11-23 10:52
This issue looks to be fixed, closing.

**Closed by AnErrupTion** 2021-11-23 10:52 UTC
Labels: bug
