### ISSUE TITLE
HIDPI support

### ISSUE THREAD

**Issue by CHJ85** [SartoxSoftware/audacium#91] opened 2022-01-11 06:53 UTC
Hi there. HIDPi is kind of a mess, as some apps do not scale right.
On my 4K monitor, the buttons in Audacium are very tiny.
For most apps that doesn't support HIDPI, I can use the command "QT_DEVICE_PIXEL_RATIO=2 QT_AUTO_SCREEN_SCALE_FACTOR=true" before the program I'm executing.
But because I'm using the AppImage build of Audacium, this does not work because AppImages are containerized.
So do you think you could fix this in the next version?
Thanks for your great work.

**Comment by AnErrupTion** [comment] 2022-01-12 05:39
It wouldn't work for 2 reasons-
First, like you said, AppImages are containerized, but also the fact that Audacium is compiled with GTK and not Qt.

Also this is a duplicate of #62.

**Closed by AnErrupTion** 2022-01-12 05:39 UTC

**Comment by CHJ85** [comment] 2022-01-12 06:12
Okay thanks. Sorry, I didn't mean to post a duplicate.
