### ISSUE TITLE
Doesn't start

### ISSUE THREAD

**Issue by DD-Indeed** [SartoxSoftware/audacium#45] opened 2021-07-26 13:37 UTC
Installed the software, and it doesn't start. The splash screen pops up, but nothing happens after that. Been trying administrator mode with the starting but no luck with that either.

Win10 x64

**Comment by Grabstertv** [comment] 2021-07-26 14:19
Can confirm. Same issue here. Program won't launch.

**Comment by stariwinkle** [comment] 2021-07-31 18:52
Same problem here.

Win11 22000.100 x64

**Comment by k1tsunee** [comment] 2021-07-31 21:05
Yep, same here.
Windows 10 21H1 19043.1110

**Comment by TimJentzsch** [comment] 2021-08-04 17:14
Same here, crashes with Segmentation fault.

**Comment by BorniPL** [comment] 2021-08-20 15:48
Same. Splash logo appears, process is loading and it is dropped soon after.

**Comment by bascurtiz** [comment] 2021-08-21 11:07
@BorniPL @TimJentzsch @k1tsunee @stariwinkle @Grabstertv @DD-Indeed 
Can you try this one and let us know if it works proper: 
https://github.com/ewanm89/audacium/releases/tag/3.0.4-alpha-2021-07-17
Thank you.

**Comment by DD-Indeed** [comment] 2021-08-21 11:31
> 
> 
> @BorniPL @TimJentzsch @k1tsunee @stariwinkle @Grabstertv @DD-Indeed
> Can you try this one and let us know if it works proper:
> https://github.com/ewanm89/audacium/releases/tag/3.0.4-alpha-2021-07-17
> Thank you.

Yup, this did the trick, works now.

**Comment by BorniPL** [comment] 2021-08-21 15:42
Yes - installed this one on top of the old one and it works.

**Comment by jt15s** [comment] 2021-09-04 10:00
Had the same issue on Windows 11 build 22000.176 and installing that alpha solved the issue.

**Comment by jt15s** [comment] 2021-09-04 10:17
Any chance we could have some sort of stable release to fix that issue? It's quite a critical one that stops people from using the app.

**Comment by JimFlasch** [comment] 2021-09-27 01:48
Did not work for me - also got an error message about how it could not find any recording or playback devices.

**Comment by AyrA** [comment] 2021-11-15 16:34
## Error details

	Faulting application name: audacium.exe, version: 3.0.4.0, time stamp: 0x60ec39c5
	Faulting module name: audacium.exe, version: 3.0.4.0, time stamp: 0x60ec39c5
	Exception code: 0xc0000005
	Fault offset: 0x000000000070292f
	Faulting process ID: 0x5bb8
	Faulting application start time: 0x01d7da3e544a31bb
	Faulting application path: C:\Program Files\Audacium\audacium.exe
	Faulting module path: C:\Program Files\Audacium\audacium.exe
	Report ID: a54f880b-4d5f-4f2a-83bc-7189770b722f
	Faulting package full name: 
	Faulting package-relative application ID: 

## XML View

	<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
		<System>
			<Provider Name="Application Error" /> 
			<EventID Qualifiers="0">1000</EventID> 
			<Version>0</Version> 
			<Level>2</Level> 
			<Task>100</Task> 
			<Opcode>0</Opcode> 
			<Keywords>0x80000000000000</Keywords> 
			<TimeCreated SystemTime="2021-11-15T16:32:08.4853561Z" /> 
			<EventRecordID>31052</EventRecordID> 
			<Correlation /> 
			<Execution ProcessID="0" ThreadID="0" /> 
			<Channel>Application</Channel> 
			<Computer>DALEK</Computer> 
			<Security /> 
		</System>
		<EventData>
			<Data>audacium.exe</Data> 
			<Data>3.0.4.0</Data> 
			<Data>60ec39c5</Data> 
			<Data>audacium.exe</Data> 
			<Data>3.0.4.0</Data> 
			<Data>60ec39c5</Data> 
			<Data>c0000005</Data> 
			<Data>000000000070292f</Data> 
			<Data>5bb8</Data> 
			<Data>01d7da3e544a31bb</Data> 
			<Data>C:\Program Files\Audacium\audacium.exe</Data> 
			<Data>C:\Program Files\Audacium\audacium.exe</Data> 
			<Data>a54f880b-4d5f-4f2a-83bc-7189770b722f</Data> 
			<Data /> 
			<Data /> 
		</EventData>
	</Event>

**Comment by AnErrupTion** [comment] 2021-11-16 22:35
Duplicate of #40, closing.

**Closed by AnErrupTion** 2021-11-16 22:35 UTC
